# Generated by Django 4.2.4 on 2023-11-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_homevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='subscription_expiry',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
